config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/index'
  root 'homes#index'
  resources :homes
  resources :home1
  resources :colleges do
	  resources :departments do
	  	resources :lab_specilities
	  	resources :cources
	  	resources :staffs
	  	resources :subjects
  		resources :students do
  			resources :marks
  			resources :attendences
  		end
	  end
	end
	resources :students
	resources :departments
	resources :marks
  resources :attendences 
  resources :staffs
  resources :cources 
  resources :lab_specilities
  resources :subjects
  resources :departments do
    resources :lab_specilities
    resources :cources
    resources :staffs
    resources :subjects
    resources :students do
      resources :marks
      resources :attendences
    end
  end
  resources :students do
    resources :marks
    resources :attendences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :student
  before_save :set_absent
	before_save :set_average
	before_save :set_exam_eligibility
end
	def set_absent
		self.absent =(self.total_hours.to_i-self.present.to_i)
	end
  
  def set_average
  	self.average =(self.total_hours.to_i-self.absent.to_i)
  end
  def set_exam_eligibility
  	if self.average.to_i >=50
  		self.exam_eligibility = "yes"
  	else
  		self.exam_eligibility ="No"
  	end
  	
  end

app/models/college.rb
class College < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :cources
	has_many :staffs
	has_many :students, dependent: :destroy
	validates :college_name,:location,:college_type,:university, presence: :true
	validates :college_code, uniqueness: :true
end

app/models/cource.rb
class Cource < ApplicationRecord
  belongs_to :college
  belongs_to :department
  validates :cource, presence: :true, uniqueness: :true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :college
  has_many :lab_specilities, dependent: :destroy
  has_many :cources, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :students, dependent: :destroy
  validates :department_name,:department_code,presence: :true, uniqueness: :true
end

app/models/lab_specility.rb
class LabSpecility < ApplicationRecord
  belongs_to :department
  
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  before_save :set_result
  validates :mark,presence: :true

  def set_result
  	if self.mark.to_i >= 35
  		self.result = "Pass"
    else
  		self.result = "Fail"
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
  belongs_to :college
  validates :staff_name,:posission,:contact_no,:email_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :college
  belongs_to :department
  has_many :marks, dependent: :destroy
  has_many :attendences, dependent: :destroy
  validates :register_no,:adhar_no,:pan_no, uniqueness: :true
  validates :student_name,:dob,:hslc_perscentage,:hsc_perscentage,:accomadation,:district,:state,:date_of_joining, presence: :true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  validates :subject,:subject_code, presence: :true
  validates :subject,:subject_code, uniqueness: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :student
  has_one :department
  has_one :college
  ADMIN = 1
  COLLEGE = 2
  STAFF = 3
  STUDENT = 4
  DEPARTMENT = 5
end

app/controllers/marks_controller.rb
class MarksController < BaseController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]
  before_action :set_students, only: [:new, :edit, :update, :create]
  before_action :set_student
  def index
    if @college.present? && @department.present? && @student.present?
      @marks = Mark.where(college_id: params[:college_id],department_id: params[:department_id],student_id: params[:student_id]).order(mark: :asc)
    elsif @department.present? && @student.present?
      @marks = Mark.where(department_id: params[:department_id],student_id: params[:student_id]).order(mark: :asc)
    elsif @student.present?
      @marks = Mark.where(student_id: params[:student_id]).order(mark: :asc)
    else
      @marks = Mark.all.order(mark: :asc)
    end
  end
  def show
  end

  def new
    @mark = Mark.new
  end

  def edit
  end

  def create
    @mark = Mark.new(mark_params)
      if @mark.save
        if @college.present? && @department.present? && @student.present?
          redirect_to college_department_student_marks_path(@college, @department,@student)
        elsif @department.present?
          redirect_to department_student_marks_path(@department,@student)
        elsif @student.present?
          redirect_to student_marks_path(@student) 
        else
          redirect_to marks_path 
        end
      else
        render 'new' 
      end
  end
  def update
      if @mark.update(mark_params)
        if @college.present? && @department.present? && @student.present?
        redirect_to college_department_student_marks_path(@college, @department,@student)
        elsif @department.present?
          redirect_to department_student_marks_path(@department,@student)
        elsif @student.present?
          redirect_to student_marks_path(@student)
        else
          redirect_to marks_path
        end
      else
        render 'edit'
      end
  end

  def destroy
    @mark.destroy
    if @college.present? && @department.present? && @student.present?
      redirect_to college_department_student_marks_path(@college, @department,@student)
    elsif @department.present?
      redirect_to department_student_marks_path(@department,@student)
    elsif @student.present?
      redirect_to student_marks_path(@student) 
    else
      redirect_to marks_path
    end
  end

  private
    def set_mark
      @mark = Mark.find(params[:id])
    end
    def set_students
      @colleges = College.pluck(:college_name,:id)
      @departments = Department.pluck(:department_name,:id)
      @students = Student.pluck(:student_name,:id)
      @subjects = Subject.pluck(:subject,:id)
      
    end
    def set_student
      @college = College.find_by(id: params[:college_id])
      @department = Department.find_by(id: params[:department_id])
      @student = Student.find_by(id: params[:student_id])
      @subject = Subject.find_by(id: params[:subject_id])
    end

    def mark_params
      params.require(:mark).permit(:student_id, :subject, :year, :mark, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/cources_helper.rb
module CourcesHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/marks/_form.html.erb
<style >
  label{color: red;}
</style>
<%= form_with(model: [@college,@department,@student,mark], local: true) do |form| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <form class="form-horizontal" action="/action_page.php">
      <div class="form-group">
        <%if @college.present? && @department.present? && @student.present? %>
          <%= form.hidden_field :student_id,value: params[:student_id]%>
        <%else%>
          <label class="control-label col-sm-2" for=":student_id">Student Id</label>
          <div class="col-sm-8">
            <%= form.select :student_id,options_for_select(@students,mark.student_id),{include_blank:true},{class: 'form-control'} %>
          </div>
        <%end%>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="subject">Subject</label>
        <div class="col-sm-8">
            <%= form.select :subject,options_for_select(@subjects,mark.subject),{include_blank:true},{class: 'form-control'} %>
          </div>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="year">Year</label>
        <div class="col-sm-4">
          <%= form.select :year,options_for_select([["I-Year", 1],["II-Year", 2],["III-Year", 3],["IV-Year", 4]],mark.year),{include_blank:true},{class: 'form-control'} %>
        </div>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="mark">Mark</label>
        <div class="col-sm-8">
          <%= form.number_field :mark, class: "form-control", placeholder: "Enter Your Mark"%>
        </div>
      </div><br><br>

      <div class="form-group" align="center">        
        <div class="col-sm-offset-2 col-sm-8">
          <button type="submit" class="btn btn-success">Submit the Student Marks Deatails</button>
        </div>
      </div><br><br>
    </form>
  </div>
<% end %>

app/views/marks/edit.html.erb
<style >
	body{background: url("<%= asset_path 'img5.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
	div{text-align: center;}
</style>
<body>
	<h1>Editing Student Marks Deatails</h1>
	<div>
		<%= render 'form', mark: @mark %>
		<%if @college.present? && @department.present? && @student.present? %>
			<%= link_to 'Show', college_department_student_mark_path(@college,@department,@student,@mark),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',college_department_student_marks_path(@college,@department,@student,@mark),class:"btn btn-warning",style:"color:black;" %>
		<%elsif  @department.present? && @student.present? %>
			<%= link_to 'Show', department_student_mark_path(@department,@student,@mark),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',department_student_marks_path(@department,@student,@mark),class:"btn btn-warning",style:"color:black;" %>
		<%elsif   @student.present? %>
			<%= link_to 'Show', student_mark_path(@student,@mark),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',student_marks_path(@student,@mark),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Show', mark_path,class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back', marks_path ,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
	
</body>

app/views/marks/index.html.erb
<style >
  body{background: url("<%= asset_path 'bc.png' %>");}
  h1{ font-family: bold;font-size: 4.5em;text-align: center;}
  div{text-align: center;}
  th{text-align: center;}
</style>
<h1>Marks</h1>
<div>
  <%if @college.present? && @department.present? && @student.present? %>
    <%= link_to 'Add Marks', new_college_department_student_mark_path(@college, @department,@student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', college_department_student_path(@college,@department,@student),class: "btn btn-warning",style:"color:black;" %>
  <%elsif @department.present? && @student.present? %>
    <%= link_to 'Add Marks', new_department_student_mark_path( @department,@student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', department_student_path(@department,@student),class: "btn btn-warning",style:"color:black;" %>
  <%elsif @student.present? %>
    <%= link_to 'Add Marks', new_student_mark_path( @student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', student_path(@student),class: "btn btn-warning",style:"color:black;" %>
  <%else%>
    <%= link_to 'back', department_path(@department),class: "btn btn-warning",style:"color:black;" %>
  <% end -%>
</div><br>

<table class="table table-striped table-bordered ">
  <thead >
    <tr class="table-success">
      <th>S.NO</th>
      <th>Student</th>
      <th>Year</th>
      <th>Mark</th>
      <th>Result</th>
      <th colspan="3">Deatails</th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each_with_index do |mark,i| %>
      <tr class="table-warning">
        <td><%= i+1 %></td>
        <td><%= mark.student.student_name %></td>
        <td><%= mark.year %></td>
        <td><%= mark.mark %></td>
        <td><%= mark.result %></td>
        <%if @college.present? && @department.present? && @student.present? %>
          <td><%= link_to 'Show', college_department_student_mark_path(@college,@department,@student,mark),class: "btn btn-info",style:"color:black;" %>    
              <%= link_to 'Edit', edit_college_department_student_mark_path(@college,@department,@student,mark),class: "btn btn-primary",style:"color:black;" %>    
              <%= link_to 'Destroy', college_department_student_mark_path(@college,@department,@student,mark),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @department.present? && @student.present? %>
          <td><%= link_to 'Show', department_student_mark_path(@department,@student,mark),class: "btn btn-info",style:"color:black;" %>    
              <%= link_to 'Edit', edit_department_student_mark_path(@department,@student,mark),class: "btn btn-primary",style:"color:black;" %>    
              <%= link_to 'Destroy', department_student_mark_path(@department,@student,mark),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @student.present? %>
          <td><%= link_to 'Show', student_mark_path(@student,mark),class: "btn btn-info",style:"color:black;" %>    
              <%= link_to 'Edit', edit_student_mark_path(@student,mark),class: "btn btn-primary",style:"color:black;" %>    
              <%= link_to 'Destroy', student_mark_path(@student,mark),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', marks_path(mark),class: "btn btn-info",style:"color:black;" %>
              <%= link_to 'Edit', edit_mark_path(mark),class: "btn btn-primary",style:"color:black;" %>
              <%= link_to 'Destroy', mark_path(mark),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/marks/new.html.erb
<style >
	body{background: url("<%= asset_path '113.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
</style>
<body>
	<h1>New Student Marks Enter</h1><br>
	<%= render 'form', mark: @mark %>
	<div align="center">
		<%if @college.present? && @department.present? && @student.present? %>
			<%= link_to 'Back',college_department_student_marks_path(@college, @department,@student),class:"btn btn-warning",style:"color:black;" %>
		<%else %>
			<%if @department.present? && @student.present? %>
				<%= link_to 'Back',department_student_marks_path(@department,@student),class:"btn btn-warning",style:"color:black;" %>
			<%elsif  @student.present? %>
				<%= link_to 'Back',student_marks_path(@student),class:"btn btn-warning",style:"color:black;" %>
			<%else%>
				<%= link_to 'Back', marks_path,class:"btn btn-warning",style:"color:black;" %>
			<% end -%>
		<% end -%>
	</div>
</body>

app/views/marks/show.html.erb
<style >
  body{background: url("<%= asset_path '5.jpg' %>");}
  strong{color: #91c29c;font-family: bild;font-size: 1em;text-align: center;}
  p{color: blue;font-size: 1em;}
  h1{color: red;font-family: bold;}
</style>
<div align="center">
  <h1>Student Marks Deatails</h1>

  <p>
    <strong>Student:</strong>
    <%= @mark.student.student_name %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= @mark.subject%>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @mark.year %>
  </p>

  <p>
    <strong>Mark:</strong>
    <%= @mark.mark %>
  </p>

  <p>
    <strong>Result:</strong>
    <%= @mark.result %>
  </p>
</div>
<div align="center">
  <%if @college.present? && @department.present? && @student.present? %>
    <%= link_to 'Edit', edit_college_department_student_mark_path(@college,@department,@student,@mark),class: "btn btn-success",style:"color:black;font-family:bold;" %> |
    <%= link_to 'Back', college_department_student_marks_path(@college,@department,@student,@mark),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%elsif  @department.present? && @student.present? %>
    <%= link_to 'Back', department_student_marks_path(@department,@student,@mark),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%elsif  @student.present? %>
    <%= link_to 'Back', student_marks_path(@student,@mark),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%else%>
    <%= link_to'back', marks_path,class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%end%>
</div>