config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/index'
  root 'homes#index'
  resources :homes
  resources :home1
  resources :colleges do
	  resources :departments do
	  	resources :lab_specilities
	  	resources :cources
	  	resources :staffs
	  	resources :subjects
  		resources :students do
  			resources :marks
  			resources :attendences
  		end
	  end
	end
	resources :students
	resources :departments
	resources :marks
  resources :attendences 
  resources :staffs
  resources :cources 
  resources :lab_specilities
  resources :subjects
  resources :departments do
    resources :lab_specilities
    resources :cources
    resources :staffs
    resources :subjects
    resources :students do
      resources :marks
      resources :attendences
    end
  end
  resources :students do
    resources :marks
    resources :attendences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :student
  before_save :set_absent
	before_save :set_average
	before_save :set_exam_eligibility
end
	def set_absent
		self.absent =(self.total_hours.to_i-self.present.to_i)
	end
  
  def set_average
  	self.average =(self.total_hours.to_i-self.absent.to_i)
  end
  def set_exam_eligibility
  	if self.average.to_i >=50
  		self.exam_eligibility = "yes"
  	else
  		self.exam_eligibility ="No"
  	end
  	
  end

app/models/college.rb
class College < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :cources
	has_many :staffs
	has_many :students, dependent: :destroy
	validates :college_name,:location,:college_type,:university, presence: :true
	validates :college_code, uniqueness: :true
end

app/models/cource.rb
class Cource < ApplicationRecord
  belongs_to :college
  belongs_to :department
  validates :cource, presence: :true, uniqueness: :true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :college
  has_many :lab_specilities, dependent: :destroy
  has_many :cources, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :students, dependent: :destroy
  validates :department_name,:department_code,presence: :true, uniqueness: :true
end

app/models/lab_specility.rb
class LabSpecility < ApplicationRecord
  belongs_to :department
  
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  before_save :set_result
  validates :mark,presence: :true

  def set_result
  	if self.mark.to_i >= 35
  		self.result = "Pass"
    else
  		self.result = "Fail"
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
  belongs_to :college
  validates :staff_name,:posission,:contact_no,:email_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :college
  belongs_to :department
  has_many :marks, dependent: :destroy
  has_many :attendences, dependent: :destroy
  validates :register_no,:adhar_no,:pan_no, uniqueness: :true
  validates :student_name,:dob,:hslc_perscentage,:hsc_perscentage,:accomadation,:district,:state,:date_of_joining, presence: :true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  validates :subject,:subject_code, presence: :true
  validates :subject,:subject_code, uniqueness: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :student
  has_one :department
  has_one :college
  ADMIN = 1
  COLLEGE = 2
  STAFF = 3
  STUDENT = 4
  DEPARTMENT = 5
end

app/controllers/students_controller.rb
class StudentsController < BaseController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_departments, only: [:new, :edit, :update, :create]
  before_action :set_department

  def index
    if @college.present? && @department.present?
      @students = Student.where(college_id: params[:college_id],department_id: params[:department_id]).order(student_name: :asc)
    elsif @department.present?
      @students = Student.where(department_id: params[:department_id]).order(student_name: :asc)
    else
      @students = Student.all.order(student_name: :asc)
    end
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end
  def create
    @student = Student.new(student_params)
      if @student.save
        @user = User.create(email: @student.email, user_type: User::STUDENT, password: "password", password_confirmation: "password")
        @student.update(user_id: @user.id)
        if @college.present? && @department.present?
          redirect_to college_department_students_path(@college, @department)
        elsif @department.present?
          redirect_to department_students_path(@department)
        else
          redirect_to students_path
        end
      else
        render 'new'
      end
  end

  def update
      if @student.update(student_params)
        if @college.present? && @department.present?
          redirect_to college_department_students_path(@college, @department)
        elsif @department.present?
          redirect_to department_students_path(@department) 
       else
        redirect_to students_path
      end
      else
        render 'edit' 
    end
  end

  def destroy
    @student.destroy
    if @college.present? && @department.present?
      redirect_to college_department_students_path(@college, @department) 
    elsif @department.present?
      redirect_to department_students_path(@department)
    else
      redirect_to students_path
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end
    def set_departments
      @colleges = College.pluck(:college_name,:id)
      @departments = Department.pluck(:department_name,:id)
    end
    def set_department
      @college = College.find_by(id: params[:college_id])
      @department = Department.find_by(id: params[:department_id])
    end

    def student_params
      params.require(:student).permit(:college_id, :department_id, :user_id, :register_no, :student_name, :fathers_name, :mothers_name, :dob, :age, :email, :password, :hslc_perscentage, :hsc_perscentage, :year, :semester, :accomadation, :date_of_joining, :address1, :address2, :city, :district, :pin, :state, :adhar_no, :pan_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/cources_helper.rb
module CourcesHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/students/_form.html.erb
<style >
  label{color: red;}
</style>
<%= form_with(model: [@college,@department,student], local: true) do |form| %>
<% if student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
    <% student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <form class="form-horizontal" action="/action_page.php">
    <div class="form-group">
      <%if @college.present? && @department.present?%>
        <%= form.hidden_field :college_id,value: params[:college_id]%>
      <%else%>
        <label class="control-label col-sm-2" for=":college_id">College</label>
        <div class="col-sm-8">
          <%= form.select :college_id,options_for_select(@colleges,student.college_id),{include_blank:true},{class: 'form-control'} %>
        </div>
      <%end%>
    </div><br><br>
    <div class="form-group">
      <%if @college.present? && @department.present?%>
        <%= form.hidden_field :department_id,value: params[:department_id]%>
      <%else%>
        <label class="control-label col-sm-2" for="department_id">Department</label>
        <div class="col-sm-8">
          <%= form.select :department_id,options_for_select(@departments,student.department_id),{include_blank:true},{class: 'form-control'} %>
        </div>
      <% end -%>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="register_no">Register No</label>
      <div class="col-sm-8">
        <%= form.text_field :register_no, class: "form-control", placeholder: "Enter Register No"%>
      </div>
    </div><br><br>
    
    <div class="form-group">
      <label class="control-label col-sm-2" for="student_name">Student Name</label>
      <div class="col-sm-8">
        <%= form.text_field :student_name, class: "form-control", placeholder: "Enter Your Name"%>
      </div>
    </div><br><br>
    
    <div class="form-group">
      <label class="control-label col-sm-2" for="fathers_name">Fathers Name</label>
      <div class="col-sm-8">
        <%= form.text_field :fathers_name, class: "form-control", placeholder: "Enter Fathers Name"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="mothers_name">Mothers Name</label>
      <div class="col-sm-8">
        <%= form.text_field :mothers_name, class: "form-control", placeholder: "Enter Mothers Name"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="dob">Date of Birth</label>
      <div class="col-sm-3">
        <%= form.date_field :dob, class: "form-control"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="gender">Gender</label>
      <div class="form-group">
        <label class="mr-3" >
            <input type="radio" class="mr-1" name="gender"> Male
        </label>
        <label class="mr-3">
            <input type="radio" class="mr-1" name="gender"> Female
        </label>
        <label class="mr-3">
            <input type="radio" class="mr-1" name="gender"> Others
        </label>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="age">Age</label>
      <div class="col-sm-3">
        <%= form.number_field :age, class: "form-control", placeholder: "Enter Your Age"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Email Id</label>
      <div class="col-sm-3">
        <%= form.email_field :email, class: "form-control", placeholder: "Enter The Email"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="hslc_perscentage">HSLC Perscentage</label>
      <div class="col-sm-3">
        <%= form.text_field :hslc_perscentage, class: "form-control", placeholder: "Enter HSLC Perscentage"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="hsc_perscentage">HSC Perscentage</label>
      <div class="col-sm-3">
        <%= form.text_field :hsc_perscentage, class: "form-control", placeholder: "Enter HSC Perscentage"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="year">Year</label>
      <div class="col-sm-4">
        <%= form.select :year,options_for_select([["I-Year", 1],["II-Year", 2],["III-Year", 3],["IV-Year", 4]],student.year),{include_blank:true},{class: 'form-control'} %>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="semester">Semester</label>
      <div class="col-sm-4">
        <%= form.select :semester,options_for_select([["1-sem",1],["2-sem",2],["3-sem",3],["4-sem",4],["5-sem",5],["6-sem",6],["7-sem",7],["8-sem",8]],student.semester),{include_blank:true},{class: 'form-control'} %>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="accomadation">Accomadation</label>
      <div class="col-sm-4">
        <%= form.select :accomadation,options_for_select(["Dayscholer","Hostel"],student.accomadation),{include_blank:true},{class: 'form-control'} %>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="date_of_joining">Date Of Joining</label>
      <div class="col-sm-4">
        <%= form.date_field :date_of_joining, class: "form-control", placeholder: "Select YourJoining Date"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="address1">Address 1</label>
      <div class="col-sm-6">
        <%= form.text_field :address1, class: "form-control", placeholder: "Enter Address1"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="address2">Address 2</label>
      <div class="col-sm-6">
        <%= form.text_field :address2, class: "form-control", placeholder: "Enter Address2"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="city">City</label>
      <div class="col-sm-6">
        <%= form.text_field :city, class: "form-control", placeholder: "Enter City"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="district">District</label>
      <div class="col-sm-4">
        <%= form.select :district,options_for_select(["Chennai","Trichy","Coiambathur","Madurai","Tirunelveli","Perambalur","Ariyalur","Salem"],student.district),{include_blank:true},{class: 'form-control'} %>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="state">State</label>
      <div class="col-sm-4">
        <%= form.select :state,options_for_select(["Tamil Nadu","Karnataka","Kerala","Andra","Dheli","Kolkatha","M.P","U.P","Jarkand","Mumbai"],student.state),{include_blank:true},{class: 'form-control'} %>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="pin">Pin Number</label>
      <div class="col-sm-4">
        <%= form.text_field :pin, class: "form-control", placeholder: "Enter Pin Number"%>
      </div>
    </div><br><br>

    <div class="form-group">
      <label class="control-label col-sm-2" for="adhar_no">Adhar Number</label>
      <div class="col-sm-6">
        <%= form.text_field :adhar_no, class: "form-control", placeholder: "Enter Adhar Number"%>
      </div>
    </div><br><br>


    <div class="form-group">
      <label class="control-label col-sm-2" for="pan_no">PAN Number</label>
      <div class="col-sm-6">
        <%= form.text_field :pan_no, class: "form-control", placeholder: "Enter PAN Number"%>
      </div>
    </div><br><br><br>

    <div class="form-group" align="center">        
      <div class="col-sm-offset-2 col-sm-8">
        <button type="submit" class="btn btn-success">Submit the Student Deatails</button>
      </div>
    </div><br><br>
  </form>
</div>
<% end %>

app/views/students/edit.html.erb
<style >
	body{background: url("<%= asset_path 'img5.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
	div{text-align: center;}
</style>
<body>
	<h1>Editing Student</h1>
	<div>
		<%= render 'form', student: @student %>
		<%if @college.present? && @department.present?%>
			<%= link_to 'Show', college_department_student_path(@college,@department),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',college_department_students_path(@college,@department),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present?%>
			<%= link_to 'Show', department_student_path(@department),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',department_students_path(@department),	class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Show',student_path,class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back', students_path ,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
	
</body>

app/views/students/index.html.erb
<style >
  body{background: url("<%= asset_path 'bc.png' %>");}
  h1{ font-family: bold;font-size: 4.5em;text-align: center;}
  div{text-align: center;}
  th{text-align: center;}
</style>
<h1>Students</h1>
<div>
  <%if @college.present? && @department.present?%>
    <%= link_to 'New Student', new_college_department_student_path(@college, @department),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', college_department_path(@college,@department),class: "btn btn-warning",style:"color:black;" %>
  <%else%>
    <%if current_user.user_type == User::ADMIN%>
      <%= link_to 'New Student', new_student_path,class: "btn btn-info",style:"color:black;" %>

      <%= link_to 'back', colleges_path,class: "btn btn-warning",style:"color:black;" %>
    <%else %>
      <%if current_user.user_type == User::DEPARTMENT%>
        <%= link_to 'New Student', new_department_student_path(@department),class: "btn btn-info",style:"color:black;" %>

        <%= link_to 'back', department_path(@department),class: "btn btn-warning",style:"color:black;" %>
      <% end -%>
    <% end -%>
  <%end%>
</div><br>

<table class="table table-striped table-bordered ">
  <thead>
    <tr class="table-success">
      <th>S.No</th>
      <th>Student Register No</th>
      <th>Student name</th>
      <th>Email</th>
      <th colspan="3">Deatails</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each_with_index do |student,i| %>
      <tr class="table-warning">
        <td><%= i+1 %></td>
        <td><%= student.register_no %></td>
        <td><%= student.student_name %></td>
        <td><%= student.email %></td>
        <%if @college.present? && @department.present?%>
          <td><%= link_to 'View Full Deatails', college_department_student_path(@college,@department,student),class: "btn btn-info",style:"color:black;" %>
              <%= link_to 'Edit', edit_college_department_student_path(@college,@department,student),class: "btn btn-primary",style:"color:black;" %>
              <%= link_to 'Delete', college_department_student_path(@college,@department,student),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @department.present?%>
          <td><%= link_to 'View Full Deatails', department_student_path(@department,student),class: "btn btn-info",style:"color:black;" %>
                <%= link_to 'Edit', edit_department_student_path(@department,student),class: "btn btn-primary",style:"color:black;" %>
                <%= link_to 'Delete', department_student_path(@department,student),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'View Full Deatails', student,class: "btn btn-info",style:"color:black;" %>
              <%= link_to 'Edit', edit_student_path(student) ,class: "btn btn-primary",style:"color:black;"%>
              <%= link_to 'Delete', student,class: "btn btn-d anger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<style >
	body{background: url("<%= asset_path '113.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
</style>
<body>
	<h1>New Student Create</h1>
	<%= render 'form', student: @student %>
	<div align="center">
		<%if @college.present? && @department.present?%>
			<%= link_to 'Back',college_department_students_path(@college, @department),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present?%>
			<%= link_to 'Back',department_students_path(@department),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Back', students_path,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
</body>

app/views/students/show.html.erb
 <style >
  body{background: url("<%= asset_path '5.jpg' %>");}
  strong{color: #91c29c;font-family: bild;font-size: 1em;text-align: center;}
  p{color: blue;font-size: 1em;}
  h1{color: red;font-family: bold;}
</style>
<div align="center">
  <h1>Students Deatails</h1>
  <div>
    <%if @college.present? && @department.present? && @student.present?%>
      <%= link_to 'Back', college_department_students_path,class: "btn btn-warning",style:"color:black;font-family:bold;" %>
      <%= link_to 'marks',college_department_student_marks_path(@college,@department,@student),class: "btn btn-success",style:"color:black;font-family:bold;"%>     |    
      <%= link_to 'atttendence',college_department_student_attendences_path(@college,@department,@student),class: "btn btn-primary",style:"color:black;font-family:bold;"%>|
    <%elsif @department.present? && @student.present? %>
      <%= link_to 'Back',department_students_path(@department,@student),class:"btn btn-warning",style:"color:black;" %>
      <%= link_to 'marks',department_student_marks_path(@department,@student),class: "btn btn-success",style:"color:black;font-family:bold;"%>     |    
      <%= link_to 'atttendence',department_student_attendences_path(@department,@student),class: "btn btn-primary",style:"color:black;font-family:bold;"%>|
    <%elsif @student.present? %>
      <%= link_to 'marks',student_marks_path(@student),class: "btn btn-success",style:"color:black;font-family:bold;"%>     |    
      <%= link_to 'atttendence',student_attendences_path(@student),class: "btn btn-primary",style:"color:black;font-family:bold;"%>|
    <%else%>
    <%= link_to 'back',students_path,class: "btn btn-warning",style:"color:black;font-family:bold;"%>
      <%= link_to 'marks', marks_path,class: "btn btn-success",style:"color:black;font-family:bold;"%>
      <%= link_to 'Attendence', attendences_path,class: "btn btn-success",style:"color:black;font-family:bold;"%>
    <% end -%>
  </div><br>

  <p>
    <strong>college Name:</strong>
    <%= @student.college.college_name %>
  </p>

  <p>
    <strong>Department Name:</strong>
    <%= @student.department.department_name%>
  </p>

  <p>
    <strong>Register No:</strong>
    <%= @student.register_no %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @student.email %>
  </p>

  <p>
    <strong>Student name:</strong>
    <%= @student.student_name %>
  </p>

  <p>
    <strong>Fathers name:</strong>
    <%= @student.fathers_name %>
  </p>

  <p>
    <strong>Mothers name:</strong>
    <%= @student.mothers_name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= @student.dob %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @student.gender %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @student.age %>
  </p>

  <p>
    <strong>Hslc perscentage:</strong>
    <%= @student.hslc_perscentage %>
  </p>

  <p>
    <strong>Hsc perscentage:</strong>
    <%= @student.hsc_perscentage %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @student.year %>
  </p>

  <p>
    <strong>Semester:</strong>
    <%= @student.semester %>
  </p>

  <p>
    <strong>Accomadation:</strong>
    <%= @student.accomadation %>
  </p>

  <p>
    <strong>Date of joining:</strong>
    <%= @student.date_of_joining %>
  </p>

  <p>
    <strong>Address1:</strong>
    <%= @student.address1 %>
  </p>

  <p>
    <strong>Address2:</strong>
    <%= @student.address2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @student.city %>
  </p>

  <p>
    <strong>District:</strong>
    <%= @student.district %>
  </p>

  <p>
    <strong>Pin:</strong>
    <%= @student.pin %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @student.state %>
  </p>

  <p>
    <strong>Adhar no:</strong>
    <%= @student.adhar_no %>
  </p>

  <p>
    <strong>Pan no:</strong>
    <%= @student.pan_no %>
  </p>
</div>
<div align="center">
  <%if @college.present? && @department.present? %>
    
  <%else%>
    
  <%end%>
</div>