config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/index'
  root 'homes#index'
  resources :homes
  resources :home1
  resources :colleges do
	  resources :departments do
	  	resources :lab_specilities
	  	resources :cources
	  	resources :staffs
	  	resources :subjects
  		resources :students do
  			resources :marks
  			resources :attendences
  		end
	  end
	end
	resources :students
	resources :departments
	resources :marks
  resources :attendences 
  resources :staffs
  resources :cources 
  resources :lab_specilities
  resources :subjects
  resources :departments do
    resources :lab_specilities
    resources :cources
    resources :staffs
    resources :subjects
    resources :students do
      resources :marks
      resources :attendences
    end
  end
  resources :students do
    resources :marks
    resources :attendences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :student
  before_save :set_absent
	before_save :set_average
	before_save :set_exam_eligibility
end
	def set_absent
		self.absent =(self.total_hours.to_i-self.present.to_i)
	end
  
  def set_average
  	self.average =(self.total_hours.to_i-self.absent.to_i)
  end
  def set_exam_eligibility
  	if self.average.to_i >=50
  		self.exam_eligibility = "yes"
  	else
  		self.exam_eligibility ="No"
  	end
  	
  end

app/models/college.rb
class College < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :cources
	has_many :staffs
	has_many :students, dependent: :destroy
	validates :college_name,:location,:college_type,:university, presence: :true
	validates :college_code, uniqueness: :true
end

app/models/cource.rb
class Cource < ApplicationRecord
  belongs_to :college
  belongs_to :department
  validates :cource, presence: :true, uniqueness: :true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :college
  has_many :lab_specilities, dependent: :destroy
  has_many :cources, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :students, dependent: :destroy
  validates :department_name,:department_code,presence: :true, uniqueness: :true
end

app/models/lab_specility.rb
class LabSpecility < ApplicationRecord
  belongs_to :department
  
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  before_save :set_result
  validates :mark,presence: :true

  def set_result
  	if self.mark.to_i >= 35
  		self.result = "Pass"
    else
  		self.result = "Fail"
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
  belongs_to :college
  validates :staff_name,:posission,:contact_no,:email_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :college
  belongs_to :department
  has_many :marks, dependent: :destroy
  has_many :attendences, dependent: :destroy
  validates :register_no,:adhar_no,:pan_no, uniqueness: :true
  validates :student_name,:dob,:hslc_perscentage,:hsc_perscentage,:accomadation,:district,:state,:date_of_joining, presence: :true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  validates :subject,:subject_code, presence: :true
  validates :subject,:subject_code, uniqueness: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :student
  has_one :department
  has_one :college
  ADMIN = 1
  COLLEGE = 2
  STAFF = 3
  STUDENT = 4
  DEPARTMENT = 5
end

app/controllers/cources_controller.rb
class CourcesController < BaseController
  before_action :set_cource, only: [:show, :edit, :update, :destroy]
  before_action :set_departments, only: [:new, :edit, :update, :crete]
  before_action :set_department

  def index
    if @college.present? && @department.present?
      @cources = Cource.where(college_id: params[:college_id],department_id: params[:department_id]).order(cource: :asc)
    elsif @department.present?
      @cources= Cource.where(department_id: params[:department_id]).order(cource: :asc)
    end
  end

  def show
  end

  def new
    @cource = Cource.new
  end

  def edit
  end

  def create
    @cource = Cource.new(cource_params)

    if @cource.save
      if @college.present? && @department.present? 
        redirect_to college_department_cources_path(@college, @department)
      elsif @department.present?
        redirect_to department_cources_path(@department) 
      else
        redirect_to cources_path
      end 
    else
       render 'new'
    end
  end

  def update
    if @cource.update(cource_params)
      if @college.present? && @department.present? 
        redirect_to college_department_cources_path(@college, @department)
      elsif @department.present?
        redirect_to department_cources_path(@department) 
      else
        redirect_to cources_path
      end
    else
      render 'edit'
    end
  end
  def destroy
    @cource.destroy
    if @college.present? && @department.present? 
      redirect_to college_department_cources_path(@college, @department)
    elsif @department.present?
      redirect_to department_cources_path(@department)  
    else
      redirect_to cources_path
    end 
  end

  private
    def set_cource
      @cource = Cource.find(params[:id])
    end
    def set_departments
      @colleges = College.pluck(:college_name,:id)
      @departments = Department.all.pluck(:department_name,:id)
    end
    def set_department
      @department = Department.find_by(id: params[:department_id])
      @college = College.find_by(id: params[:college_id])
    end

    def cource_params
      params.require(:cource).permit(:college_id, :department_id, :cource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/cources_helper.rb
module CourcesHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/cources/_form.html.erb
<style >
  label{color: red;}
</style>
<%= form_with(model: [@college,@department,cource], local: true) do |form| %>
  <% if cource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cource.errors.count, "error") %> prohibited this cource from being saved:</h2>

      <ul>
      <% cource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <form class="form-horizontal" action="/action_page.php">
      <div class="form-group">
        <%if @college.present? && @department.present?%>
          <%= form.hidden_field :college_id,value: params[:college_id]%>
        <%else%>
          <label class="control-label col-sm-2" for=":college_id">College Id</label>
          <div class="col-sm-8">
            <%= form.select :college_id,options_for_select(@colleges,cource.college_id),{include_blank:true},{class: 'form-control'} %>
          </div>
        <%end%>
      </div><br><br>
      <div class="form-group">
        <%if @college.present? && @department.present?%>
          <%= form.hidden_field :department_id,value: params[:department_id]%>
        <%else%>
          <label class="control-label col-sm-2" for="department_id">Department Id</label>
          <div class="col-sm-8">
            <%= form.select :department_id,options_for_select(@departments,cource.department_id),{include_blank:true},{class: 'form-control'} %>
          </div>
        <% end -%>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="cource">Cource</label>
        <div class="col-sm-4">
          <%= form.select :cource,options_for_select(["BE","B.TECH","ME","M.TECH"],cource.cource),{include_blank:true},{class: 'form-control'} %>
        </div>
      </div><br><br>

      <div class="form-group" align="center">        
        <div class="col-sm-offset-2 col-sm-8">
          <button type="submit" class="btn btn-success">Submit The Cource Deatails</button>
        </div>
      </div><br><br>
    </form>
  </div>
<% end %>

app/views/cources/edit.html.erb
<style >
	body{background: url("<%= asset_path 'img5.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
	div{text-align: center;}
</style>
<body>
	<h1>Editing Cource Deatails</h1>
	<div>
		<%= render 'form', cource: @cource %>
		<%if @college.present? && @department.present?%>
			<%= link_to 'Show', college_department_cource_path(@college,@department,@cource),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',college_department_cources_path(@college,@department,@cource),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present?%>
			<%= link_to 'Show', department_cource_path(@department,@cource),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back',department_cources_path(@department,@cource),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Show',cource_path(cource),class:"btn btn-success",style:"color:black;" %> |
			<%= link_to 'Back', cource_path(cource) ,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
	
</body>

app/views/cources/index.html.erb
<style >
  body{background: url("<%= asset_path 'bc.png' %>");}
  h1{ font-family: bold;font-size: 4.5em;text-align: center;}
  div{text-align: center;}
  th{text-align: center;}
</style>
<h1>Cources</h1>
<div>
  <%if @college.present? && @department.present?%>
    <%= link_to 'Add New Cource', new_college_department_cource_path(@college, @department),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', college_department_path(@college,@department),class: "btn btn-warning",style:"color:black;" %>
  <%elsif @department.present?%>
    <%= link_to 'Add New Cource', new_department_cource_path(@department),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', department_path(@department),class: "btn btn-warning",style:"color:black;" %>
  <%else%>
    <%= link_to 'Add New Cource', new_cource_path,class: "btn btn-info",style:"color:black;" %>
    <%= link_to 'Back', department_path(@department),class:"btn btn-default",style:"color:black;"  %> 
  <%end%>
</div><br>

<table class="table table-striped table-bordered ">
  <thead>
    <tr class="table-success">
      <th>S.No</th>
      <th>College</th>
      <th>Department</th>
      <th>Cource</th>
      <th colspan="3">Deatails</th>
    </tr>
  </thead>

  <tbody>
    <% @cources.each_with_index do |cource,i| %>
      <tr class="table-warning">
        <td><%= i+1 %></td>
        <td><%= cource.college.college_name %></td>
        <td><%= cource.department.department_name %></td>
        <td><%= cource.cource %></td>
        <%if @college.present? && @department.present?%>
          <td><%= link_to 'View The Deatails', college_department_cource_path(@college, @department,cource),class: "btn btn-info",style:"color:black;" %>    
              <%= link_to 'Edit', edit_college_department_cource_path(@college, @department,cource),class: "btn btn-primary",style:"color:black;" %>    
              <%= link_to 'Delete', college_department_cource_path(@college, @department,cource),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @department.present?%>
          <td><%= link_to 'View The Deatails', department_cource_path(@department,cource),class: "btn btn-info",style:"color:black;" %>    
              <%= link_to 'Edit', edit_department_cource_path(@department,cource),class: "btn btn-primary",style:"color:black;" %>    
              <%= link_to 'Delete', department_cource_path(@department,cource),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'View The Deatails', cource_path(cource),class: "btn btn-info",style:"color:black;" %>
              <%= link_to 'Edit', edit_cource_path(cource) ,class: "btn btn-primary",style:"color:black;"%>
              <%= link_to 'Delete', cource_path(cource),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cources/new.html.erb
<style >
	body{background: url("<%= asset_path '113.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
</style>
<body>
	<h1>Add New Cource</h1><br>
	<%= render 'form', cource: @cource %>
	<div align="center">
		<%if @college.present? && @department.present?%>
			<%= link_to 'Back',college_department_cources_path(@college, @department),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present?%>
			<%= link_to 'Back',department_cources_path(@department),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Back', college_department_path,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
</body>

app/views/cources/show.html.erb
 <style >
  body{background: url("<%= asset_path '5.jpg' %>");}
  strong{color: #91c29c;font-family: bild;font-size: 1em;text-align: center;}
  p{color: blue;font-size: 1em;}
  h1{color: red;font-family: bold;}
</style>
<div align="center">
  <h1>Cource Deatails</h1>

	<p>
	  <strong>College:</strong>
	  <%= @cource.college.college_name %>
	</p>

	<p>
	  <strong>Department:</strong>
	  <%= @cource.department.department_name %>
	</p>

	<p>
	  <strong>Cource:</strong>
	  <%= @cource.cource %>
	</p>
</div>
<div align="center">
  <%if @college.present? && @department.present?%>
  	<%= link_to 'edit',edit_college_department_cource_path(@college,@department,@cource),class: "btn btn-success",style:"color:black;font-family:bold;" %>
    <%= link_to 'Back', college_department_cources_path(@college,@department,@cource),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%elsif @department.present?%>
  	<%= link_to 'edit',edit_department_cource_path(@department,@cource),class: "btn btn-success",style:"color:black;font-family:bold;" %>
    <%= link_to 'Back', department_cources_path(@department,@cource),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%else%>
    <%= link_to 'edit',edit_student_path,class: "btn btn-success",style:"color:black;font-family:bold;" %>
    <%= link_to'back', colleges_path,class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <% end -%>
</div><br>