config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/index'
  root 'homes#index'
  resources :homes
  resources :home1
  resources :colleges do
	  resources :departments do
	  	resources :lab_specilities
	  	resources :cources
	  	resources :staffs
	  	resources :subjects
  		resources :students do
  			resources :marks
  			resources :attendences
  		end
	  end
	end
	resources :students
	resources :departments
	resources :marks
  resources :attendences 
  resources :staffs
  resources :cources 
  resources :lab_specilities
  resources :subjects
  resources :departments do
    resources :lab_specilities
    resources :cources
    resources :staffs
    resources :subjects
    resources :students do
      resources :marks
      resources :attendences
    end
  end
  resources :students do
    resources :marks
    resources :attendences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :student
  before_save :set_absent
	before_save :set_average
	before_save :set_exam_eligibility
end
	def set_absent
		self.absent =(self.total_hours.to_i-self.present.to_i)
	end
  
  def set_average
  	self.average =(self.total_hours.to_i-self.absent.to_i)
  end
  def set_exam_eligibility
  	if self.average.to_i >=50
  		self.exam_eligibility = "yes"
  	else
  		self.exam_eligibility ="No"
  	end
  	
  end

app/models/college.rb
class College < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :cources
	has_many :staffs
	has_many :students, dependent: :destroy
	validates :college_name,:location,:college_type,:university, presence: :true
	validates :college_code, uniqueness: :true
end

app/models/cource.rb
class Cource < ApplicationRecord
  belongs_to :college
  belongs_to :department
  validates :cource, presence: :true, uniqueness: :true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :college
  has_many :lab_specilities, dependent: :destroy
  has_many :cources, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :students, dependent: :destroy
  validates :department_name,:department_code,presence: :true, uniqueness: :true
end

app/models/lab_specility.rb
class LabSpecility < ApplicationRecord
  belongs_to :department
  
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  before_save :set_result
  validates :mark,presence: :true

  def set_result
  	if self.mark.to_i >= 35
  		self.result = "Pass"
    else
  		self.result = "Fail"
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :department
  belongs_to :college
  validates :staff_name,:posission,:contact_no,:email_id, presence:true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :college
  belongs_to :department
  has_many :marks, dependent: :destroy
  has_many :attendences, dependent: :destroy
  validates :register_no,:adhar_no,:pan_no, uniqueness: :true
  validates :student_name,:dob,:hslc_perscentage,:hsc_perscentage,:accomadation,:district,:state,:date_of_joining, presence: :true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  validates :subject,:subject_code, presence: :true
  validates :subject,:subject_code, uniqueness: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :student
  has_one :department
  has_one :college
  ADMIN = 1
  COLLEGE = 2
  STAFF = 3
  STUDENT = 4
  DEPARTMENT = 5
end

app/controllers/attendences_controller.rb
class AttendencesController < BaseController
  before_action :set_attendence, only: [:show, :edit, :update, :destroy]
  before_action :set_students, only: [:new, :edit, :update, :create]
  before_action :set_student
  def index
    if @college.present? && @department.present? && @student.present?
      @attendences = Mark.where(college_id: params[:college_id],department_id: params[:department_id],student_id: params[:student_id]).order(attendence: :asc)
    elsif @department.present? && @student.present?
      @attendences = Mark.where(department_id: params[:department_id],student_id: params[:student_id]).order(attendence: :asc)
    elsif @student.present?
      @attendences = Mark.where(student_id: params[:student_id]).order(attendence: :asc)
    else
      @attendences = Mark.all.order(subject: :asc)
    end
  end

  def show
  end

  def new
    @attendence = Attendence.new
  end

  def edit
  end

  def create
    @attendence = Attendence.new(attendence_params)
      if @attendence.save
        if @college.present? && @department.present? && @student.present?
          redirect_to college_department_student_attendences_path(@college,@department,@student)
        elsif @department.present?
          redirect_to department_student_attendences_path(@department,@student)
        elsif @student.present?
          redirect_to student_attendences_path(@student)
        else
          redirect_to attendences_path 
        end
      else
        render 'new'
      end
  end

  def update
      if @college.present? && @department.present? && @student.present?
        redirect_to college_department_student_attendences_path(@college,@department,@student)
      elsif @department.present?
        redirect_to department_student_attendences_path(@department,@student)
      elsif @student.present?
        redirect_to student_attendences_path(@student)
      else
        render 'edit'
      end
  end
  def destroy
    if @college.present? && @department.present? && @student.present?
      redirect_to college_department_student_attendences_path(@college,@department,@student)
    elsif @department.present?
      redirect_to department_student_attendences_path(@department,@student)
    elsif @student.present?
      redirect_to student_attendences_path(@student)
    end   
  end

  private
    def set_attendence
      @attendence = Attendence.find(params[:id])
    end
     def set_students
      @colleges = College.pluck(:college_name,:id)
      @departments = Department.pluck(:department_name,:id)
      @students = Student.pluck(:student_name,:id)
      
    end
    def set_student
      @college = College.find_by(id: params[:college_id])
      @department = Department.find_by(id: params[:department_id])
      @student = Student.find_by(id: params[:student_id])
    end


    def attendence_params
      params.require(:attendence).permit(:student_id, :year, :semester, :total_hours, :present, :absent, :average, :exam_eligibility)
    end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/cources_helper.rb
module CourcesHelper
end

app/helpers/home1_helper.rb
module Home1Helper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/attendences/_form.html.erb
<style >
  label{color: red;}
</style>
<%= form_with(model: [@college,@department,@student,attendence], local: true) do |form| %>
  <% if attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% attendence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <form class="form-horizontal" action="/action_page.php">
      <div class="form-group">
        <%if @college.present? && @department.present? && @student.present? %>
          <%= form.hidden_field :student_id,value: params[:student_id]%>
        <%else%>
          <label class="control-label col-sm-2" for=":student_id">Student Id</label>
          <div class="col-sm-8">
            <%= form.select :student_id,options_for_select(@students,attendence.student_id),{include_blank:true},{class: 'form-control'} %>
          </div>
        <%end%>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="year">Year</label>
        <div class="col-sm-4">
          <%= form.select :year,options_for_select([["I-Year", 1],["II-Year", 2],["III-Year", 3],["IV-Year", 4]],attendence.year),{include_blank:true},{class: 'form-control'} %>
        </div>
      </div><br><br>

      <div class="form-group">
      <label class="control-label col-sm-2" for="semester">Semester</label>
        <div class="col-sm-4">
          <%= form.select :semester,options_for_select([["1-sem",1],["2-sem",2],["3-sem",3],["4-sem",4],["5-sem",5],["6-sem",6],["7-sem",7],["8-sem",8]],attendence.semester),{include_blank:true},{class: 'form-control'} %>
        </div>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="total_hours">Total Hours</label>
        <div class="col-sm-4">
          <%= form.number_field :total_hours, class: "form-control", placeholder: "Enter Your Total Hours"%>
        </div>
      </div><br><br>

      <div class="form-group">
        <label class="control-label col-sm-2" for="present">Present Hours</label>
        <div class="col-sm-4">
          <%= form.number_field :present, class: "form-control", placeholder: "Enter Your Present Hours"%>
        </div>
      </div><br><br>

      <div class="form-group" align="center">        
        <div class="col-sm-offset-2 col-sm-8">
          <button type="submit" class="btn btn-success">Submit the Student Attendence Deatails</button>
        </div>
      </div><br><br>
    </form>
  </div>
<% end %>

app/views/attendences/edit.html.erb
<style >
	body{background: url("<%= asset_path 'img5.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
	div{text-align: center;}
</style>
<body>
	<p id="notice"><%= notice %></p>
	<h1>Editing Student Attendence Deatails</h1>
	<div>
		<%= render 'form', attendence: @attendence %>
		<%if @college.present? && @department.present? && @student.present? %>
			<%= link_to 'Back',college_department_student_attendences_path(@college,@department,@student,@attendence),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present? && @student.present? %>
			<%= link_to 'Back',department_student_attendences_path(@department,@student,@attendence),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @student.present? %>
			<%= link_to 'Back',student_attendences_path(@student,@attendence),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Back', attendences_path(@attendence),class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
	
</body>

app/views/attendences/index.html.erb
<style >
  body{background: url("<%= asset_path 'bc.png' %>");}
  h1{ font-family: bold;font-size: 4.5em;text-align: center;}
  div{text-align: center;}
  th{text-align: center;}
</style>
<p id="notice"><%= notice %></p>
<h1>Attendence Deatails</h1>
<div>
  <%if @college.present? && @department.present? && @student.present? %>
    <%= link_to 'Add Attendence', new_college_department_student_attendence_path(@college, @department,@student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', college_department_student_path(@college,@department,@student),class: "btn btn-warning",style:"color:black;" %>
  <%elsif @department.present? && @student.present? %>
    <%= link_to 'Add Attendence', new_department_student_attendence_path( @department,@student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', department_student_path(@department,@student),class: "btn btn-warning",style:"color:black;" %>
  <%elsif @student.present? %>
    <%= link_to 'Add attendence', new_student_attendence_path( @student),class: "btn btn-success",style:"color:black;" %>
    <%= link_to 'back', student_path(@student),class: "btn btn-warning",style:"color:black;" %>
  <%else%>
    <%= link_to 'back', department_path(@department),class: "btn btn-warning",style:"color:black;" %>
  <%end%>
</div><br>

<table class="table table-striped table-bordered ">
  <thead >
    <tr class="table-success">
      <th>S.No</th>
      <th>Student</th>
      <th>Present</th>
      <th>Exam eligibility</th>
      <th colspan="3">Deatails</th>
    </tr>
  </thead>

  <tbody>
    <% @attendences.each_with_index do |attendence,i| %>
      <tr class="table-warning">
        <td><%= i+1 %></td>
        <td><%= attendence.student.student_name %></td>
        <td><%= attendence.present %></td>
        <td><%= attendence.exam_eligibility %></td>
        <%if @college.present? && @department.present? && @student.present? %>
          <td><%= link_to 'Show', college_department_student_attendence_path(@college,@department,@student,attendence),class: "btn btn-info",style:"color:black;"  %>    
              <%= link_to 'Edit', edit_college_department_student_attendence_path(@college,@department,@student,attendence),class: "btn btn-warning",style:"color:black;"  %>   
              <%= link_to 'Destroy', college_department_student_attendence_path(@college,@department,@student,attendence),class: "btn btn-danger",style:"color:black;" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @department.present? && @student.present? %>
          <td><%= link_to 'Show', department_student_attendence_path(@department,@student,attendence),class: "btn btn-info",style:"color:black;"  %>    
              <%= link_to 'Edit', edit_department_student_attendence_path(@department,@student,attendence),class: "btn btn-warning",style:"color:black;"  %>   
              <%= link_to 'Destroy', department_student_attendence_path(@department,@student,attendence),class: "btn btn-danger",style:"color:black;" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif @student.present? %>
          <td><%= link_to 'Show', student_attendence_path(@student,attendence),class: "btn btn-info",style:"color:black;"  %>    
              <%= link_to 'Edit', edit_student_attendence_path(@student,attendence),class: "btn btn-warning",style:"color:black;"  %>   
              <%= link_to 'Destroy', student_attendence_path(@student,attendence),class: "btn btn-danger",style:"color:black;" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', attendences_path(attendence),class: "btn btn-info",style:"color:black;" %>
              <%= link_to 'Edit', edit_attendence_path(attendence),class: "btn btn-primary",style:"color:black;" %>
              <%= link_to 'Destroy', attendence_path(attendence),class: "btn btn-danger",style:"color:black;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/attendences/new.html.erb
<style >
	body{background: url("<%= asset_path '113.jpg' %>");}
	h1{font-family: bold;color: #db34eb;text-align: center;}
</style>
<body>
	<p id="notice"><%= notice %></p>
	<h1>New Student Attendence Enter</h1><br>
	<%= render 'form', attendence: @attendence %>
	<div align="center">
		<%if @college.present? && @department.present? && @student.present? %>
			<%= link_to 'Back',college_department_student_attendences_path(@college, @department,@student),class:"btn btn-warning",style:"color:black;" %>
		<%elsif @department.present? && @student.present? %>
			<%= link_to 'Back',department_student_attendences_path( @department,@student),class:"btn btn-warning",style:"color:black;" %>
		<%elsif  @student.present? %>
			<%= link_to 'Back',student_attendences_path(@student),class:"btn btn-warning",style:"color:black;" %>
		<%else%>
			<%= link_to 'Back',attendences_path,class:"btn btn-warning",style:"color:black;" %>
		<% end -%>
	</div>
</body>

app/views/attendences/show.html.erb
<style >
  body{background: url("<%= asset_path '5.jpg' %>");}
  strong{color: #91c29c;font-family: bild;font-size: 1em;text-align: center;}
  p{color: blue;font-size: 1em;}
  h1{color: red;font-family: bold;}
</style>
<p id="notice"><%= notice %></p>
<div align="center">
  <h1>Student Attendence Deatails</h1>
  <p>
    <strong>Student:</strong>
    <%= @attendence.student.student_name %>
  </p>

  <p>
    <strong>Total hours:</strong>
    <%= @attendence.total_hours %>
  </p>

  <p>
    <strong>Present:</strong>
    <%= @attendence.present %>
  </p>

  <p>
    <strong>Absent:</strong>
    <%= @attendence.absent %>
  </p>

  <p>
    <strong>Average:</strong>
    <%= @attendence.average %>
  </p>

  <p>
    <strong>Exam eligibility:</strong>
    <%= @attendence.exam_eligibility %>
  </p>
</div>
</div>
<div align="center">
  <%if @college.present? && @department.present? && @student.present? %>
    <%= link_to 'Edit', edit_college_department_student_attendence_path(@college,@department,@student,@attendence),class: "btn btn-success",style:"color:black;font-family:bold;" %> |
    <%= link_to 'Back', college_department_student_attendences_path(@college,@department,@student,@attendence),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%elsif @department.present? && @student.present? %>
    <%= link_to 'Edit', edit_department_student_attendence_path(@department,@student,@attendence),class: "btn btn-success",style:"color:black;font-family:bold;" %> |
    <%= link_to 'Back', department_student_attendences_path(@department,@student,@attendence),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%elsif  @student.present? %>
    <%= link_to 'Edit', edit_student_attendence_path(@student,@attendence),class: "btn btn-success",style:"color:black;font-family:bold;" %> |
    <%= link_to 'Back', student_attendences_path(@student,@attendence),class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%else%>
    <%= link_to 'edit',edit_attendence_path(@attendence),class: "btn btn-success",style:"color:black;font-family:bold;" %>
    <%= link_to'back', attendences_path,class: "btn btn-warning",style:"color:black;font-family:bold;" %>
  <%end%>
</div>